#pragma once

#include <cstdint>

// Forward declarations (automatically generated)
class WindissectOpaque;
namespace Microsoft { namespace WRL { class Details; } } 
class TextSuggestionTraceLoggingTelemetry; 
namespace Windows { namespace Data { class Text; } } 
namespace Windows { class Globalization; } 
namespace std { class locale; } 
class ActivityData; class AgileGitPtr; class AutoStubBias; class BrokeredActivationBase; class CMarshaledInterface; class CSearchTextSourceWrapper; class CSearchWordBreakerWrapper; class CSearchWordSinkWrapper; class CTypeWrapper; class ConstrainedImpersonateLoggedOnUser; class Destroy; class FEATURE_LOGGED_TRAITS; class FEATURE_STATE_CHANGE_SUBSCRIPTION__; class HBITMAP__; class HBRUSH__; class HDC__; class HDESK__; class HFONT__; class HINSTANCE__; class HKEY__; class HMONITOR__; class HRGN__; class HSTRING_BUFFER__; class HSTRING__; class HWINSTA__; class HWND__; class IActivationFactory; class IClassFactory; class IInspectable; class IMtfSuggestionCandidate; class IMtfSuggestionList; class IPhraseSink; class IRpcOptions; class IStream; class IUnknown; class IWeakReference; class IWordBreaker; class IWordBreakerFeatures; class IWordSink; class IXmlReader; class Nullable; class ReleaseSRWLockExclusive; class RpcOptionsHelper; class SP; class SP_HLOCAL; class SP_MEM; class SysFreeString; class TextSuggestionTraceLogging; class TextSuggestionTraceLoggingTelemetry; class TokenRangeAndType; class WARBIRD_DELAY_LOAD; class WilFailureReport; class WilFailureReportInformation; class _BLENDFUNCTION; class _CONTEXT; class _EVENT_FILTER_DESCRIPTOR; class _EXCEPTION_RECORD; class _GROUPING_LETTER_ENTRY_const; class _GUID; class _Grp_t; class _MTF_CONTEXT_PROP; class _MTF_PRIMITIVE_PROP; class _MTF_QUERY_PROP; class _RO_REGISTRATION_COOKIE; class _RTL_RUN_ONCE; class _RTL_SRWLOCK; class _TIME_DYNAMIC_ZONE_INFORMATION; class _TIME_ZONE_INFORMATION; class _TP_CALLBACK_INSTANCE; class _TP_TIMER; class _TRIVERTEX; class _TlgReflectorTag_Param0IsProviderType; class _WNF_STATE_NAME; class _WNF_TYPE_ID; class _WNF_USER_SUBSCRIPTION; class __WIL_RTL_FEATURE_USAGE_DATA; class __WIL__WNF_STATE_NAME; class _devicemodeW; class _tlgProvider_t; class _tlgWrapSz; class _tlgWrapperByVal; class lambda_04bf9480eb9e133401c37e488ee0694a; class lambda_156f8c05752017390d6185e99ef4c093; class lambda_1feea9c82387731dd9a5bbf470c5cf36; class lambda_319d5e083f45f90dcdce5dce53cbb275; class lambda_3fdb14453883e86a37ebade6a7a0ebb0; class lambda_4df51b9394f616c3f78c1b5692913eb0; class lambda_7030d12a21dba11210293044e97fe9c7; class lambda_76078e3bf33fbe180bf3a23ea3d43c38; class lambda_7f96eb1dcf99da5daec8c2467d2d5499; class lambda_9013ee9e23efe4882b67eff5b0ecf103; class lambda_b70241e9b5ebaad244db3e52d52cab17; class lambda_c22b6d2626d3c698d0debbb5837c3742; class lambda_c2fd7731c5ae0d37e65ea73be67c0f1b; class lambda_c454d6dd31f0dee2210018772d32719f; class lambda_d7a75c1ee9f49c18f73e44c142c4183b; class lambda_e1befb086ad3257e3f042a63030725f7; class permission; class tagBITMAPINFO; class tagDRAWTEXTPARAMS; class tagLOGFONTW; class tagMONITORINFO; class tagPOINT; class tagRECT; class tagTEXT_SOURCE; class thunk; class type_info; class wil_FeatureState; class wil_details_FeatureReportingCache; class wil_details_FeatureStateCache; class wil_details_FeatureUsageSRUM; 
namespace Microsoft { namespace WRL { class ActivationFactory; class AgileRef; class ComPtr; class Details; class FtmBase; class Implements; class RuntimeClassFlags; class SimpleClassFactory; class SimpleSealedActivationFactory; } } 
namespace Microsoft { namespace WRL { namespace Wrappers { class Details; class HString; class HStringReference; class SRWLock; } } } 
namespace ReaderWriterLock { class ScopedRead; class ScopedWrite; } 
namespace Windows { class Globalization; } 
namespace Windows { namespace Data { class Text; } } 
namespace Windows { namespace Foundation { namespace Collections { class Detail; } } } 
namespace Windows { namespace Foundation { namespace Collections { namespace Internal { class detail; } } } } 
namespace Windows { namespace Internal { class AsyncCallbackBase; class CHSTRINGResult; class CMarshaledInterfaceResult; class ComTaskPoolHandler; class HResultException; class IAsyncFireCompletion; class IComPoolTask; class INilDelegate; } } 
namespace Windows { namespace Internal { namespace ComTaskPool { class CTaskWrapper; } } } 
namespace Windows { namespace System { class IUser; } } 
namespace Windows { namespace System { namespace Internal { class ISignInStateManager; } } } 
namespace Windows { namespace System { namespace UserProfile { class GlobalizationPreferences; class GlobalizationPreferencesBase; class GlobalizationPreferencesBrokered; class GlobalizationPreferencesForUser; class IGlobalizationPreferencesForUser; class IGlobalizationPreferencesStatics; class IGlobalizationPreferencesStatics2; class IGlobalizationPreferencesStatics3; } } } 
namespace std { class _Binder; class _Bt_state_t; class _Buf; class _Cmp_collate; class _Cmp_icase; class _Facet_base; class _Func_base; class _Func_class; class _Locinfo; class _Loop_vals_t; class _Node_base; class _Node_class; class _Node_rep; class _One_then_variadic_args_t; class _Ph; class _Ref_count_base; class _Regex_traits; class _Root_node; class _Sequence; class _Simple_types; class _String_const_iterator; class _String_constructor_concat_tag; class _String_iterator; class _String_val; class _Tgt_state_t; class _Tree_find_result; class _Tree_id; class _Tree_node; class _Unforced; class _Value_init_tag; class _Vb_const_iterator; class _Vb_iterator; class _Vb_reference; class _Vector_const_iterator; class _Vector_iterator; class _Vector_val; class _Wrap_alloc; class allocator; class back_insert_iterator; class bad_alloc; class bad_array_new_length; class bad_cast; class bad_weak_ptr; class basic_regex; class basic_string; class char_traits; class collate; class ctype; class default_delete; class equal_to; class exception; class function; class less; class locale; class map; class match_results; class nothrow_t; class nullptr_t; class pair; class piecewise_construct_t; class ratio; class regex_iterator; class regex_token_iterator; class regex_traits; class shared_ptr; class sub_match; class tuple; class unique_ptr; class vector; class weak_ptr; } 
namespace std { namespace chrono { class duration; class steady_clock; class time_point; } } 
namespace wil { class ActivityBase; class ActivityThreadWatcher; class CallContextInfo; class FailureInfo; class ResultException; class process_heap_deleter; class srwlock; class unique_any_t; } 
namespace wil { namespace details { class DestroyThreadPoolTimer; class FeatureStateManager; class IFailureCallback; class ResultStatus; class SystemThreadPoolMethods; class ThreadFailureCallbackHolder; class resource_policy; class shared_object; class unique_storage; } } 
namespace wil { namespace details_abi { class FeatureStateData; class ProcessLocalData; class ProcessLocalStorageData; class RawUsageIndex; class ThreadLocalData; class UsageIndexProperty; class UsageIndexes; class heap_buffer; class heap_vector; } } 
namespace wistd { class function; class integral_constant; class unique_ptr; } 
namespace wistd { namespace __function { class __base; } } 

